name: Build

on:
  push:
    branches:
      - master
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: npm install, lint, build, and test
      run: |
        npm ci
        npm run lint
        npm test
        npm run build
      env:
        CI: true

